import dotenv from "dotenv";
import { db } from "../src/lib/firebase-admin.js";

dotenv.config();

const grants = [
  {
    opportunityId: "grant_001",
    title: "DAAD Research Scholarship 2025",
    type: "scholarship",
    country: "Germany",
    organization: "DAAD",
    degree: ["master", "phd"],
    field: ["All Fields"],
    fundingType: "full",
    amount: "€850/month + tuition",
    language: "German B2 or English B2",
    minGPA: 3.0,
    minIELTS: 6.5,
    deadline: "2026-03-15",
    trustScore: 95,
    verificationStatus: "verified",
    sourceUrl: "https://www.daad.de",
    description:
      "DAAD research scholarship for international students pursuing advanced studies and research in Germany.",
    embedding: [],
    createdAt: new Date(),
  },
  {
    opportunityId: "grant_002",
    title: "Humboldt Research Fellowship",
    type: "fellowship",
    country: "Germany",
    organization: "Alexander von Humboldt Foundation",
    degree: ["phd"],
    field: ["All Fields"],
    fundingType: "full",
    amount: "€2,700/month + research costs",
    language: "English B2",
    minGPA: 3.2,
    minIELTS: 6.5,
    deadline: "2026-04-20",
    trustScore: 92,
    verificationStatus: "verified",
    sourceUrl: "https://www.humboldt-foundation.de",
    description:
      "International research fellowship for postdoctoral researchers at German institutions.",
    embedding: [],
    createdAt: new Date(),
  },
  {
    opportunityId: "grant_003",
    title: "Deutschlandstipendium",
    type: "scholarship",
    country: "Germany",
    organization: "German Universities",
    degree: ["bachelor", "master"],
    field: ["All Fields"],
    fundingType: "partial",
    amount: "€300/month",
    language: "German B1 or English B2",
    minGPA: 3.0,
    minIELTS: 6.0,
    deadline: "2026-06-01",
    trustScore: 85,
    verificationStatus: "verified",
    sourceUrl: "https://www.deutschlandstipendium.de",
    description:
      "Merit-based scholarship funded by the German government and private sponsors.",
    embedding: [],
    createdAt: new Date(),
  },
  {
    opportunityId: "grant_004",
    title: "Erasmus+ Germany Exchange (Partner Universities)",
    type: "exchange",
    country: "Germany",
    organization: "Erasmus+",
    degree: ["bachelor", "master"],
    field: ["All Fields"],
    fundingType: "partial",
    amount: "€490/month",
    language: "English B2",
    minGPA: 2.8,
    minIELTS: 6.0,
    deadline: "2026-05-10",
    trustScore: 88,
    verificationStatus: "verified",
    sourceUrl: "https://erasmus-plus.ec.europa.eu",
    description:
      "Semester exchange opportunity for eligible partner universities in Germany.",
    embedding: [],
    createdAt: new Date(),
  },
  {
    opportunityId: "grant_005",
    title: "GKS (Global Korea Scholarship) Graduate Program",
    type: "scholarship",
    country: "South Korea",
    organization: "NIIED",
    degree: ["master", "phd"],
    field: ["All Fields"],
    fundingType: "full",
    amount: "₩1,000,000/month + tuition",
    language: "Korean TOPIK preferred / English B2",
    minGPA: 3.0,
    minIELTS: 6.0,
    deadline: "2026-03-01",
    trustScore: 93,
    verificationStatus: "verified",
    sourceUrl: "https://www.studyinkorea.go.kr",
    description:
      "Fully funded scholarship for international students pursuing graduate degrees in Korea.",
    embedding: [],
    createdAt: new Date(),
  },
  {
    opportunityId: "grant_006",
    title: "KGSP Undergraduate Track (Partner Universities)",
    type: "scholarship",
    country: "South Korea",
    organization: "NIIED",
    degree: ["bachelor"],
    field: ["All Fields"],
    fundingType: "full",
    amount: "₩900,000/month + tuition",
    language: "English B2",
    minGPA: 3.0,
    minIELTS: 6.0,
    deadline: "2026-02-28",
    trustScore: 90,
    verificationStatus: "verified",
    sourceUrl: "https://www.studyinkorea.go.kr",
    description:
      "Undergraduate scholarship program for international students in South Korea.",
    embedding: [],
    createdAt: new Date(),
  },
  {
    opportunityId: "grant_007",
    title: "Korean University Research Internship",
    type: "internship",
    country: "South Korea",
    organization: "University Labs",
    degree: ["bachelor", "master"],
    field: ["STEM"],
    fundingType: "partial",
    amount: "₩500,000/month",
    language: "English B2",
    minGPA: 3.0,
    minIELTS: 6.0,
    deadline: "2026-07-01",
    trustScore: 78,
    verificationStatus: "pending",
    sourceUrl: "https://example.com",
    description:
      "Research internship opportunities in Korean university labs (varies by institution).",
    embedding: [],
    createdAt: new Date(),
  },
  {
    opportunityId: "grant_008",
    title: "Fulbright Foreign Student Program",
    type: "scholarship",
    country: "USA",
    organization: "Fulbright",
    degree: ["master", "phd"],
    field: ["All Fields"],
    fundingType: "full",
    amount: "Tuition + stipend + travel",
    language: "English C1",
    minGPA: 3.2,
    minIELTS: 7.0,
    deadline: "2026-05-01",
    trustScore: 96,
    verificationStatus: "verified",
    sourceUrl: "https://foreign.fulbrightonline.org",
    description:
      "Prestigious fully-funded program for graduate study and research in the United States.",
    embedding: [],
    createdAt: new Date(),
  },
  {
    opportunityId: "grant_009",
    title: "Humphrey Fellowship Program",
    type: "fellowship",
    country: "USA",
    organization: "Fulbright",
    degree: ["master"],
    field: ["Public Policy", "Development", "Leadership"],
    fundingType: "full",
    amount: "Tuition + stipend + travel",
    language: "English C1",
    minGPA: 3.0,
    minIELTS: 7.0,
    deadline: "2026-06-15",
    trustScore: 94,
    verificationStatus: "verified",
    sourceUrl: "https://www.humphreyfellowship.org",
    description:
      "Non-degree fellowship for experienced professionals to enhance leadership skills in the USA.",
    embedding: [],
    createdAt: new Date(),
  },
  {
    opportunityId: "grant_010",
    title: "USA University Exchange Semester",
    type: "exchange",
    country: "USA",
    organization: "Partner Universities",
    degree: ["bachelor", "master"],
    field: ["All Fields"],
    fundingType: "partial",
    amount: "Partial tuition waiver",
    language: "English B2",
    minGPA: 3.0,
    minIELTS: 6.5,
    deadline: "2026-08-01",
    trustScore: 80,
    verificationStatus: "pending",
    sourceUrl: "https://example.com",
    description:
      "Exchange semester options at partner universities in the USA (availability varies).",
    embedding: [],
    createdAt: new Date(),
  }
];

async function main() {
  for (const g of grants) {
    await db
      .collection("opportunities")
      .doc(g.opportunityId)
      .set(g, { merge: true });
    console.log(`✓ Added: ${g.title}`);
  }
  console.log(`Done. Seeded ${grants.length} grants.`);
}

main().catch((err) => {
  console.error("Seed error:", err);
  process.exitCode = 1;
});

