name: EduFund Daily Scraper

on:
  schedule:
    # Toshkent vaqti bilan (UTC+5) 08:00 -> UTC bo'yicha 03:00 bo'ladi
    - cron: '0 3 * * *'
  workflow_dispatch: # Qo'lda run qilish tugmasini ham qo'shamiz

jobs:
  scrape-grants:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 firebase-admin

      - name: Run Scraper Script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "Skript ishga tushirilmoqda..."
          python scraper.py
          echo "Skript vazifasini to'liq tugatdi!"
